# -*- coding: utf-8 -*-
"""Sensor_Updated_C_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HOkx5KM5jZt4WxRuQ8VQksr8bB9ZXT5Z

# 🚗 IMU Turn Detection System — Python → C
**Original Python code:** `left_turn.py`  
**Target:** Embed on Arduino / Raspberry Pi  
**Dataset:** 6-axis IMU CSV file

---

## ⚙️ How This Works (Big Picture)
This notebook converts a Python left-turn detection algorithm into C — step by step.
The C code is compiled and run directly inside Colab using `gcc`.

**Flow:**
"""

!git clone https://github.com/sravani-a11y/sensor.git

import os
os.listdir('sensor')

# Commented out IPython magic to ensure Python compatibility.
# %cd sensor
!python left_turn.py --csv imu_6axis_data_20260308_084155_Trip2_Left.csv

"""## Step 1 — CSV Reader

**What it does:** Opens the CSV, scans the header row, finds the correct columns
for `timestamp`, `gx(dps)`, and `az(g)`, then loads all rows into memory.

**Expected output:** `Loaded 1750 valid rows` with first/last 5 rows shown.

### ⚠️ Watch Out For:
- If it says `Required columns not found` → your CSV column names are different.
  Open your CSV, check the exact header names, and update the candidate lists
  inside `parse_header()` in the C code.
- `MAX_ROWS = 5000` — increase this if your CSV has more than 5000 rows.
- Rows with non-numeric gx or az values are automatically skipped.

### 🔩 Hardware Note:
On Arduino/Raspberry Pi, this step is replaced by **reading directly from the IMU sensor**
over I2C/SPI — no CSV needed. The column detection logic becomes unnecessary.
"""





# Commented out IPython magic to ensure Python compatibility.
# %%writefile step1_read_csv.c
# #include <stdio.h>
# #include <stdlib.h>
# #include <string.h>
# 
# #define MAX_ROWS 5000
# #define MAX_COLS 20
# #define MAX_COL_LEN 64
# #define MAX_LINE_LEN 512
# 
# /* ── data store ── */
# static double gx[MAX_ROWS];
# static double az[MAX_ROWS];
# static char   timestamps[MAX_ROWS][32];
# static int    n_rows = 0;
# 
# /* ── column indices (found by header scan) ── */
# static int col_gx = -1;
# static int col_az = -1;
# static int col_ts = -1;
# 
# /* ── strip whitespace + quotes from a token ── */
# void clean_token(char *s) {
#     /* remove leading spaces/quotes */
#     int i = 0;
#     while (s[i] == ' ' || s[i] == '"') i++;
#     memmove(s, s + i, strlen(s + i) + 1);
#     /* remove trailing spaces/quotes/newline */
#     int len = (int)strlen(s);
#     while (len > 0 &&
#            (s[len-1] == ' ' || s[len-1] == '"' ||
#             s[len-1] == '\n' || s[len-1] == '\r'))
#         s[--len] = '\0';
# }
# 
# /* ── normalize: lowercase, remove spaces/underscores/parens ── */
# void normalize(const char *src, char *dst, int maxlen) {
#     int j = 0;
#     for (int i = 0; src[i] && j < maxlen - 1; i++) {
#         char c = src[i];
#         if (c >= 'A' && c <= 'Z') c += 32;   /* to lower */
#         if (c == ' ' || c == '_' || c == '-' ||
#             c == '(' || c == ')' || c == '/')
#             continue;                          /* skip */
#         dst[j++] = c;
#     }
#     dst[j] = '\0';
# }
# 
# /* ── split a CSV line into tokens, return count ── */
# int split_csv(char *line, char tokens[][MAX_COL_LEN], int max_tokens) {
#     int count = 0;
#     char *p = line;
#     while (count < max_tokens) {
#         char *start = p;
#         /* find next comma or end */
#         while (*p && *p != ',') p++;
#         int len = (int)(p - start);
#         if (len >= MAX_COL_LEN) len = MAX_COL_LEN - 1;
#         strncpy(tokens[count], start, len);
#         tokens[count][len] = '\0';
#         clean_token(tokens[count]);
#         count++;
#         if (*p == ',') p++;
#         else break;
#     }
#     return count;
# }
# 
# /* ── parse header, find column indices ── */
# int parse_header(char *line, int *ts_col, int *gx_c, int *az_c) {
#     char tokens[MAX_COLS][MAX_COL_LEN];
#     int n = split_csv(line, tokens, MAX_COLS);
# 
#     *ts_col = -1; *gx_c = -1; *az_c = -1;
# 
#     for (int i = 0; i < n; i++) {
#         char norm[MAX_COL_LEN];
#         normalize(tokens[i], norm, MAX_COL_LEN);
# 
#         /* timestamp candidates */
#         if (*ts_col < 0 &&
#             (strcmp(norm,"timestamp")==0 || strcmp(norm,"time")==0 ||
#              strcmp(norm,"datetime")==0))
#             *ts_col = i;
# 
#         /* gx candidates */
#         if (*gx_c < 0 &&
#             (strcmp(norm,"gxdps")==0 || strcmp(norm,"gx")==0 ||
#              strcmp(norm,"gyrox")==0 || strcmp(norm,"gyroxdps")==0))
#             *gx_c = i;
# 
#         /* az candidates */
#         if (*az_c < 0 &&
#             (strcmp(norm,"azg")==0  || strcmp(norm,"az")==0 ||
#              strcmp(norm,"accz")==0 || strcmp(norm,"accelz")==0))
#             *az_c = i;
#     }
# 
#     printf("Header scan (%d cols):\n", n);
#     printf("  timestamp col : %d\n", *ts_col);
#     printf("  gx col        : %d\n", *gx_c);
#     printf("  az col        : %d\n", *az_c);
# 
#     return (*gx_c >= 0 && *az_c >= 0) ? 0 : -1;
# }
# 
# /* ── load CSV ── */
# int load_csv(const char *path) {
#     FILE *f = fopen(path, "r");
#     if (!f) { perror("fopen"); return -1; }
# 
#     char line[MAX_LINE_LEN];
# 
#     /* read header */
#     if (!fgets(line, sizeof(line), f)) {
#         fprintf(stderr, "Empty file\n");
#         fclose(f); return -1;
#     }
#     if (parse_header(line, &col_ts, &col_gx, &col_az) != 0) {
#         fprintf(stderr, "Could not find gx / az columns.\n");
#         fclose(f); return -1;
#     }
# 
#     /* read data rows */
#     n_rows = 0;
#     while (fgets(line, sizeof(line), f) && n_rows < MAX_ROWS) {
#         char tokens[MAX_COLS][MAX_COL_LEN];
#         int n = split_csv(line, tokens, MAX_COLS);
# 
#         if (n <= col_gx || n <= col_az) continue;  /* short row */
# 
#         /* skip rows where gx or az is non-numeric */
#         char *endptr;
#         double gx_val = strtod(tokens[col_gx], &endptr);
#         if (endptr == tokens[col_gx]) continue;
#         double az_val = strtod(tokens[col_az], &endptr);
#         if (endptr == tokens[col_az]) continue;
# 
#         gx[n_rows] = gx_val;
#         az[n_rows] = az_val;
# 
#         if (col_ts >= 0 && n > col_ts)
#             strncpy(timestamps[n_rows], tokens[col_ts], 31);
#         else
#             snprintf(timestamps[n_rows], 31, "row_%d", n_rows);
# 
#         n_rows++;
#     }
# 
#     fclose(f);
#     return n_rows;
# }
# 
# /* ════════════════════════════════
#    MAIN — Step 1 test
#    ════════════════════════════════ */
# int main(void) {
#     const char *csv_path = "imu_6axis_data_20260308_084155_Trip2_Left.csv";
# 
#     printf("=== Step 1: CSV Reader ===\n\n");
#     int rows = load_csv(csv_path);
#     if (rows < 0) return 1;
# 
#     printf("\nLoaded %d valid rows.\n", rows);
#     printf("\nFirst 5 rows (timestamp | gx | az):\n");
#     printf("%-30s  %10s  %10s\n", "Timestamp", "gx(dps)", "az(g)");
#     printf("%-30s  %10s  %10s\n",
#            "------------------------------", "----------", "----------");
# 
#     int preview = rows < 5 ? rows : 5;
#     for (int i = 0; i < preview; i++)
#         printf("%-30s  %10.4f  %10.4f\n", timestamps[i], gx[i], az[i]);
# 
#     printf("\nLast 5 rows:\n");
#     printf("%-30s  %10s  %10s\n", "Timestamp", "gx(dps)", "az(g)");
#     printf("%-30s  %10s  %10s\n",
#            "------------------------------", "----------", "----------");
#     for (int i = rows - 5; i < rows; i++)
#         printf("%-30s  %10.4f  %10.4f\n", timestamps[i], gx[i], az[i]);
# 
#     return 0;
# }

!gcc step1_read_csv.c -o step1 -lm
!./step1





"""## Step 2 — Moving Average (Smoothing)

**What it does:** Applies a 5-sample trailing moving average to both `gx` and `az`
to reduce sensor noise before detection.

**Expected output:** Table comparing raw vs smoothed values. Smoothing kicks in from row 0.

### ⚠️ Watch Out For:
- `SMOOTH_K = 5` matches the Python default — don't change unless you change it in Python too.
- The first few rows use fewer than 5 samples (min_periods=1 behavior) — this is intentional and matches Python exactly.
- If your sensor is very noisy, you can increase `SMOOTH_K` to 7 or 10, but re-validate against Python output.

### 🔩 Hardware Note:
On embedded hardware, this runs as a **ring buffer** — only the last 5 samples
are kept in memory at any time. This is memory-efficient for microcontrollers.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile step2_moving_avg.c
# #include <stdio.h>
# #include <stdlib.h>
# #include <string.h>
# 
# #define MAX_ROWS     5000
# #define MAX_COLS       20
# #define MAX_COL_LEN    64
# #define MAX_LINE_LEN  512
# #define SMOOTH_K        5   /* must match Python's DEFAULT_SMOOTH = 5 */
# 
# /* ── raw data ── */
# static double gx_raw[MAX_ROWS];
# static double az_raw[MAX_ROWS];
# static char   timestamps[MAX_ROWS][32];
# static int    n_rows = 0;
# 
# /* ── smoothed output ── */
# static double gx_smooth[MAX_ROWS];
# static double az_smooth[MAX_ROWS];
# 
# /* ── column indices ── */
# static int col_gx = -1;
# static int col_az = -1;
# static int col_ts = -1;
# 
# /* ════════════════════════════════════════
#    CSV helpers  (same as Step 1)
#    ════════════════════════════════════════ */
# void clean_token(char *s) {
#     int i = 0;
#     while (s[i] == ' ' || s[i] == '"') i++;
#     memmove(s, s + i, strlen(s + i) + 1);
#     int len = (int)strlen(s);
#     while (len > 0 &&
#            (s[len-1]==' ' || s[len-1]=='"' ||
#             s[len-1]=='\n'|| s[len-1]=='\r'))
#         s[--len] = '\0';
# }
# 
# void normalize(const char *src, char *dst, int maxlen) {
#     int j = 0;
#     for (int i = 0; src[i] && j < maxlen-1; i++) {
#         char c = src[i];
#         if (c>='A' && c<='Z') c += 32;
#         if (c==' '||c=='_'||c=='-'||c=='('||c==')'||c=='/') continue;
#         dst[j++] = c;
#     }
#     dst[j] = '\0';
# }
# 
# int split_csv(char *line, char tokens[][MAX_COL_LEN], int max_tokens) {
#     int count = 0;
#     char *p = line;
#     while (count < max_tokens) {
#         char *start = p;
#         while (*p && *p != ',') p++;
#         int len = (int)(p - start);
#         if (len >= MAX_COL_LEN) len = MAX_COL_LEN - 1;
#         strncpy(tokens[count], start, len);
#         tokens[count][len] = '\0';
#         clean_token(tokens[count]);
#         count++;
#         if (*p == ',') p++; else break;
#     }
#     return count;
# }
# 
# int parse_header(char *line) {
#     char tokens[MAX_COLS][MAX_COL_LEN];
#     int n = split_csv(line, tokens, MAX_COLS);
#     col_ts = col_gx = col_az = -1;
#     for (int i = 0; i < n; i++) {
#         char norm[MAX_COL_LEN];
#         normalize(tokens[i], norm, MAX_COL_LEN);
#         if (col_ts < 0 &&
#             (strcmp(norm,"timestamp")==0||strcmp(norm,"time")==0||
#              strcmp(norm,"datetime")==0)) col_ts = i;
#         if (col_gx < 0 &&
#             (strcmp(norm,"gxdps")==0||strcmp(norm,"gx")==0||
#              strcmp(norm,"gyrox")==0||strcmp(norm,"gyroxdps")==0)) col_gx = i;
#         if (col_az < 0 &&
#             (strcmp(norm,"azg")==0||strcmp(norm,"az")==0||
#              strcmp(norm,"accz")==0||strcmp(norm,"accelz")==0)) col_az = i;
#     }
#     return (col_gx >= 0 && col_az >= 0) ? 0 : -1;
# }
# 
# int load_csv(const char *path) {
#     FILE *f = fopen(path, "r");
#     if (!f) { perror("fopen"); return -1; }
#     char line[MAX_LINE_LEN];
#     if (!fgets(line, sizeof(line), f)) { fclose(f); return -1; }
#     if (parse_header(line) != 0) {
#         fprintf(stderr, "Required columns not found.\n");
#         fclose(f); return -1;
#     }
#     n_rows = 0;
#     while (fgets(line, sizeof(line), f) && n_rows < MAX_ROWS) {
#         char tokens[MAX_COLS][MAX_COL_LEN];
#         int n = split_csv(line, tokens, MAX_COLS);
#         if (n <= col_gx || n <= col_az) continue;
#         char *ep;
#         double gv = strtod(tokens[col_gx], &ep);
#         if (ep == tokens[col_gx]) continue;
#         double av = strtod(tokens[col_az], &ep);
#         if (ep == tokens[col_az]) continue;
#         gx_raw[n_rows] = gv;
#         az_raw[n_rows] = av;
#         if (col_ts >= 0 && n > col_ts)
#             strncpy(timestamps[n_rows], tokens[col_ts], 31);
#         else
#             snprintf(timestamps[n_rows], 31, "row_%d", n_rows);
#         n_rows++;
#     }
#     fclose(f);
#     return n_rows;
# }
# 
# /* ════════════════════════════════════════
#    Moving average
#    Mirrors Python:
#      pd.Series(x).rolling(window=k, min_periods=1).mean()
#    → for index i, average the last min(i+1, k) samples
#    ════════════════════════════════════════ */
# void moving_average(const double *in, double *out, int n, int k) {
#     for (int i = 0; i < n; i++) {
#         int start = i - k + 1;
#         if (start < 0) start = 0;          /* min_periods=1 behaviour */
#         int count = i - start + 1;
#         double sum = 0.0;
#         for (int j = start; j <= i; j++)
#             sum += in[j];
#         out[i] = sum / count;
#     }
# }
# 
# /* ════════════════════════════════════════
#    MAIN — Step 2 test
#    ════════════════════════════════════════ */
# int main(void) {
#     const char *csv_path = "imu_6axis_data_20260308_084155_Trip2_Left.csv";
# 
#     printf("=== Step 2: Moving Average (k=%d) ===\n\n", SMOOTH_K);
# 
#     if (load_csv(csv_path) < 0) return 1;
#     printf("Loaded %d rows.\n\n", n_rows);
# 
#     /* apply smoothing */
#     moving_average(gx_raw, gx_smooth, n_rows, SMOOTH_K);
#     moving_average(az_raw, az_smooth, n_rows, SMOOTH_K);
# 
#     /* ── print comparison table: raw vs smoothed ── */
#     printf("%-6s  %10s  %10s  %10s  %10s\n",
#            "Row", "gx_raw", "gx_smooth", "az_raw", "az_smooth");
#     printf("%-6s  %10s  %10s  %10s  %10s\n",
#            "------","----------","----------","----------","----------");
# 
#     /* first 8 rows */
#     printf("-- first 8 rows --\n");
#     int show = n_rows < 8 ? n_rows : 8;
#     for (int i = 0; i < show; i++)
#         printf("%-6d  %10.4f  %10.4f  %10.4f  %10.4f\n",
#                i, gx_raw[i], gx_smooth[i], az_raw[i], az_smooth[i]);
# 
#     /* rows around index 678 (start of Event 1 in Python output) */
#     printf("\n-- rows 675-682 (Event 1 region) --\n");
#     for (int i = 675; i <= 682 && i < n_rows; i++)
#         printf("%-6d  %10.4f  %10.4f  %10.4f  %10.4f\n",
#                i, gx_raw[i], gx_smooth[i], az_raw[i], az_smooth[i]);
# 
#     /* verify: smoothed gx at row 678 should be negative (left turn) */
#     printf("\nSanity check at row 678:\n");
#     printf("  gx_smooth[678] = %.4f  (expect < 0 for left-turn region)\n",
#            gx_smooth[678]);
#     printf("  az_smooth[678] = %.4f\n", az_smooth[678]);
# 
#     return 0;
# }

!gcc step2_moving_avg.c -o step2 -lm
!./step2





"""## Step 3 — Rolling Window Detection

**What it does:** Slides a 40-sample window across the data. For each window,
it computes `gx_mean`, `gx_min`, and `gx_integral` and checks two sets of rules:

| Rule | gx_mean | gx_min | gx_integral |
|------|---------|--------|-------------|
| Strict | < -4.0 | < -12.0 | < -15.0 deg |
| Relaxed | < -3.0 | < -10.0 | < -12.0 deg + az_mean < -0.03 |

**Expected output:** `Triggered windows: 264` — must match Python exactly.

### ⚠️ Watch Out For:
- If triggered windows don't match Python (264), the dt estimate is likely off.
  Check `Estimated dt` — it must be `0.1020 s`.
- `WINDOW_SIZE = 40` means the first detection can only happen at row 40+.
- `gx_integral = sum(gx_window) * dt` — this is **not** a proper numerical integral,
  it's a rectangular approximation. This matches the Python implementation exactly.
- Thresholds are tuned for **this specific sensor and vehicle**. If deploying on
  different hardware, you will need to re-calibrate these values.

### 🔩 Hardware Note:
On embedded hardware, the window slides **one sample at a time** in real-time —
no need to store the entire dataset. Only 40 samples need to be in memory at once.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile step3_detection.c
# #include <stdio.h>
# #include <stdlib.h>
# #include <string.h>
# 
# #define MAX_ROWS      5000
# #define MAX_COLS        20
# #define MAX_COL_LEN     64
# #define MAX_LINE_LEN   512
# #define MAX_DETECTIONS 5000
# 
# /* ── tuning knobs ── */
# #define WINDOW_SIZE   40
# #define SMOOTH_K       5
# #define DEFAULT_DT  0.102   /* fallback; overridden by CSV timestamps */
# 
# /* ── strict thresholds ── */
# #define STRICT_GX_MEAN  -4.0
# #define STRICT_GX_MIN  -12.0
# #define STRICT_GX_INT  -15.0
# 
# /* ── relaxed thresholds ── */
# #define RELAX_GX_MEAN   -3.0
# #define RELAX_GX_MIN   -10.0
# #define RELAX_GX_INT   -12.0
# #define RELAX_AZ_MEAN   -0.03
# 
# /* ── data ── */
# static double gx_raw[MAX_ROWS];
# static double az_raw[MAX_ROWS];
# static double gx_s  [MAX_ROWS];   /* smoothed */
# static double az_s  [MAX_ROWS];
# static char   timestamps[MAX_ROWS][32];
# static int    n_rows = 0;
# 
# /* ── detection record ── */
# typedef struct {
#     int    start_idx;
#     int    end_idx;
#     double gx_mean;
#     double gx_min;
#     double gx_integral_deg;
#     double az_mean;
#     int    rule;          /* 0 = strict, 1 = relaxed */
# } DetectionWindow;
# 
# static DetectionWindow detections[MAX_DETECTIONS];
# static int n_detections = 0;
# 
# /* ── column indices ── */
# static int col_gx = -1, col_az = -1, col_ts = -1;
# 
# /* ════════════════════════════════════════
#    CSV helpers
#    ════════════════════════════════════════ */
# void clean_token(char *s) {
#     int i = 0;
#     while (s[i]==' '||s[i]=='"') i++;
#     memmove(s, s+i, strlen(s+i)+1);
#     int len=(int)strlen(s);
#     while(len>0&&(s[len-1]==' '||s[len-1]=='"'||
#                   s[len-1]=='\n'||s[len-1]=='\r'))
#         s[--len]='\0';
# }
# 
# void normalize(const char *src, char *dst, int maxlen) {
#     int j=0;
#     for(int i=0;src[i]&&j<maxlen-1;i++){
#         char c=src[i];
#         if(c>='A'&&c<='Z') c+=32;
#         if(c==' '||c=='_'||c=='-'||c=='('||c==')'||c=='/') continue;
#         dst[j++]=c;
#     }
#     dst[j]='\0';
# }
# 
# int split_csv(char *line, char tokens[][MAX_COL_LEN], int max_tokens) {
#     int count=0; char *p=line;
#     while(count<max_tokens){
#         char *start=p;
#         while(*p&&*p!=',') p++;
#         int len=(int)(p-start);
#         if(len>=MAX_COL_LEN) len=MAX_COL_LEN-1;
#         strncpy(tokens[count],start,len);
#         tokens[count][len]='\0';
#         clean_token(tokens[count]);
#         count++;
#         if(*p==',') p++; else break;
#     }
#     return count;
# }
# 
# int parse_header(char *line) {
#     char tokens[MAX_COLS][MAX_COL_LEN];
#     int n=split_csv(line,tokens,MAX_COLS);
#     col_ts=col_gx=col_az=-1;
#     for(int i=0;i<n;i++){
#         char norm[MAX_COL_LEN];
#         normalize(tokens[i],norm,MAX_COL_LEN);
#         if(col_ts<0&&(strcmp(norm,"timestamp")==0||strcmp(norm,"time")==0||
#             strcmp(norm,"datetime")==0)) col_ts=i;
#         if(col_gx<0&&(strcmp(norm,"gxdps")==0||strcmp(norm,"gx")==0||
#             strcmp(norm,"gyrox")==0||strcmp(norm,"gyroxdps")==0)) col_gx=i;
#         if(col_az<0&&(strcmp(norm,"azg")==0||strcmp(norm,"az")==0||
#             strcmp(norm,"accz")==0||strcmp(norm,"accelz")==0)) col_az=i;
#     }
#     return (col_gx>=0&&col_az>=0)?0:-1;
# }
# 
# int load_csv(const char *path) {
#     FILE *f=fopen(path,"r");
#     if(!f){perror("fopen");return -1;}
#     char line[MAX_LINE_LEN];
#     if(!fgets(line,sizeof(line),f)){fclose(f);return -1;}
#     if(parse_header(line)!=0){
#         fprintf(stderr,"Required columns not found.\n");
#         fclose(f);return -1;
#     }
#     n_rows=0;
#     while(fgets(line,sizeof(line),f)&&n_rows<MAX_ROWS){
#         char tokens[MAX_COLS][MAX_COL_LEN];
#         int n=split_csv(line,tokens,MAX_COLS);
#         if(n<=col_gx||n<=col_az) continue;
#         char *ep;
#         double gv=strtod(tokens[col_gx],&ep); if(ep==tokens[col_gx]) continue;
#         double av=strtod(tokens[col_az],&ep); if(ep==tokens[col_az]) continue;
#         gx_raw[n_rows]=gv; az_raw[n_rows]=av;
#         if(col_ts>=0&&n>col_ts)
#             strncpy(timestamps[n_rows],tokens[col_ts],31);
#         else
#             snprintf(timestamps[n_rows],31,"row_%d",n_rows);
#         n_rows++;
#     }
#     fclose(f);
#     return n_rows;
# }
# 
# /* ════════════════════════════════════════
#    Moving average
#    ════════════════════════════════════════ */
# void moving_average(const double *in, double *out, int n, int k) {
#     for(int i=0;i<n;i++){
#         int start=i-k+1; if(start<0) start=0;
#         int count=i-start+1;
#         double sum=0.0;
#         for(int j=start;j<=i;j++) sum+=in[j];
#         out[i]=sum/count;
#     }
# }
# 
# /* ════════════════════════════════════════
#    Estimate dt from timestamps
#    Looks for median gap between consecutive rows
#    ════════════════════════════════════════ */
# double estimate_dt(void) {
#     /* Try to parse HH:MM:SS.mmm or full datetime from timestamps */
#     double diffs[MAX_ROWS];
#     int    n_diffs = 0;
# 
#     for(int i=1; i<n_rows; i++){
#         /* find last ':' then seconds field */
#         const char *a = timestamps[i-1];
#         const char *b = timestamps[i];
# 
#         /* locate seconds part after second colon */
#         int col_count=0; int pa=-1,pb=-1;
#         for(int k=0;a[k];k++) if(a[k]==':'){col_count++;if(col_count==2){pa=k+1;break;}}
#         col_count=0;
#         for(int k=0;b[k];k++) if(b[k]==':'){col_count++;if(col_count==2){pb=k+1;break;}}
#         if(pa<0||pb<0) continue;
# 
#         double sa=strtod(a+pa,NULL);
#         double sb=strtod(b+pb,NULL);
# 
#         /* also grab minutes */
#         int mpa=-1,mpb=-1,cc=0;
#         for(int k=0;a[k];k++) if(a[k]==':'){cc++;if(cc==1){mpa=k+1;break;}}
#         cc=0;
#         for(int k=0;b[k];k++) if(b[k]==':'){cc++;if(cc==1){mpb=k+1;break;}}
# 
#         double mina=strtod(a+mpa,NULL);
#         double minb=strtod(b+mpb,NULL);
# 
#         double ta = mina*60.0 + sa;
#         double tb = minb*60.0 + sb;
#         double diff = tb - ta;
#         if(diff>0 && diff<2.0)
#             diffs[n_diffs++]=diff;
#     }
# 
#     if(n_diffs==0) return DEFAULT_DT;
# 
#     /* simple median via insertion sort on first n_diffs values */
#     for(int i=1;i<n_diffs;i++){
#         double key=diffs[i]; int j=i-1;
#         while(j>=0&&diffs[j]>key){diffs[j+1]=diffs[j];j--;}
#         diffs[j+1]=key;
#     }
#     return diffs[n_diffs/2];
# }
# 
# /* ════════════════════════════════════════
#    Rolling window left-turn detector
#    Mirrors Python detect_left_turn_windows()
#    ════════════════════════════════════════ */
# void detect_left_turn_windows(double dt) {
#     n_detections = 0;
# 
#     if(n_rows < WINDOW_SIZE) return;
# 
#     for(int start=0; start <= n_rows - WINDOW_SIZE; start++){
#         int end = start + WINDOW_SIZE - 1;
# 
#         /* compute window stats on smoothed data */
#         double gx_mean=0, gx_min=gx_s[start], gx_sum=0;
#         double az_mean=0;
# 
#         for(int i=start; i<=end; i++){
#             gx_sum  += gx_s[i];
#             az_mean += az_s[i];
#             if(gx_s[i] < gx_min) gx_min = gx_s[i];
#         }
#         gx_mean = gx_sum / WINDOW_SIZE;
#         az_mean = az_mean / WINDOW_SIZE;
#         double gx_integral = gx_sum * dt;   /* deg = sum(dps) * dt */
# 
#         /* strict rule */
#         int strict = (gx_mean < STRICT_GX_MEAN &&
#                       gx_min  < STRICT_GX_MIN  &&
#                       gx_integral < STRICT_GX_INT);
# 
#         /* relaxed rule */
#         int relaxed = (gx_mean < RELAX_GX_MEAN &&
#                        gx_min  < RELAX_GX_MIN  &&
#                        gx_integral < RELAX_GX_INT &&
#                        az_mean < RELAX_AZ_MEAN);
# 
#         if((strict || relaxed) && n_detections < MAX_DETECTIONS){
#             detections[n_detections].start_idx       = start;
#             detections[n_detections].end_idx         = end;
#             detections[n_detections].gx_mean         = gx_mean;
#             detections[n_detections].gx_min          = gx_min;
#             detections[n_detections].gx_integral_deg = gx_integral;
#             detections[n_detections].az_mean         = az_mean;
#             detections[n_detections].rule            = strict ? 0 : 1;
#             n_detections++;
#         }
#     }
# }
# 
# /* ════════════════════════════════════════
#    MAIN — Step 3 test
#    ════════════════════════════════════════ */
# int main(void) {
#     const char *csv_path = "imu_6axis_data_20260308_084155_Trip2_Left.csv";
# 
#     printf("=== Step 3: Rolling Window Detection ===\n\n");
# 
#     if(load_csv(csv_path) < 0) return 1;
#     printf("Loaded %d rows.\n", n_rows);
# 
#     moving_average(gx_raw, gx_s, n_rows, SMOOTH_K);
#     moving_average(az_raw, az_s, n_rows, SMOOTH_K);
# 
#     double dt = estimate_dt();
#     printf("Estimated dt : %.4f s\n", dt);
#     printf("Window size  : %d samples (%.3f s)\n\n",
#            WINDOW_SIZE, WINDOW_SIZE * dt);
# 
#     detect_left_turn_windows(dt);
# 
#     printf("Triggered windows : %d  (Python = 264)\n\n", n_detections);
# 
#     /* print first 10 detections */
#     printf("First 10 detections:\n");
#     printf("%-8s %-8s %-10s %-10s %-12s %-10s %-8s\n",
#            "Start","End","gx_mean","gx_min","gx_int(deg)","az_mean","Rule");
#     printf("%-8s %-8s %-10s %-10s %-12s %-10s %-8s\n",
#            "--------","--------","----------","----------",
#            "------------","----------","--------");
# 
#     int show = n_detections < 10 ? n_detections : 10;
#     for(int i=0; i<show; i++){
#         DetectionWindow *d = &detections[i];
#         printf("%-8d %-8d %-10.3f %-10.3f %-12.3f %-10.4f %-8s\n",
#                d->start_idx, d->end_idx,
#                d->gx_mean, d->gx_min, d->gx_integral_deg,
#                d->az_mean,
#                d->rule==0 ? "strict" : "relaxed");
#     }
# 
#     return 0;
# }

!gcc step3_detection.c -o step3 -lm
!./step3





"""## Step 4 — Merge Detections into Events

**What it does:** Multiple overlapping windows often fire for a single physical turn.
This step merges all nearby detections (within 10 samples of each other) into
one clean event with a start time, end time, and peak values.

**Expected output:** `Merged events: 6` — must match Python exactly.

### ⚠️ Watch Out For:
- `MERGE_GAP = 10` samples (~1 second) — detections closer than this are merged.
  Increase if turns are being split into multiple events. Decrease if separate turns
  are being merged together.
- Peak GX, MeanGX, and IntRot values are computed over **raw** (unsmoothed) gx —
  this matches the Python `build_event()` function exactly.

### 🔩 Hardware Note:
On hardware, merging is done using a **state machine** with a timeout counter —
if no new detection fires within MERGE_GAP samples, the event is closed and the
notification is triggered immediately.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile step4_merge_events.c
# #include <stdio.h>
# #include <stdlib.h>
# #include <string.h>
# 
# #define MAX_ROWS       5000
# #define MAX_COLS         20
# #define MAX_COL_LEN      64
# #define MAX_LINE_LEN    512
# #define MAX_DETECTIONS 5000
# #define MAX_EVENTS      500
# 
# #define WINDOW_SIZE    40
# #define SMOOTH_K        5
# #define DEFAULT_DT   0.102
# #define MERGE_GAP      10   /* samples — matches Python DEFAULT_MERGE_GAP */
# 
# #define STRICT_GX_MEAN  -4.0
# #define STRICT_GX_MIN  -12.0
# #define STRICT_GX_INT  -15.0
# #define RELAX_GX_MEAN   -3.0
# #define RELAX_GX_MIN   -10.0
# #define RELAX_GX_INT   -12.0
# #define RELAX_AZ_MEAN   -0.03
# 
# /* ── data ── */
# static double gx_raw[MAX_ROWS], az_raw[MAX_ROWS];
# static double gx_s  [MAX_ROWS], az_s  [MAX_ROWS];
# static char   timestamps[MAX_ROWS][32];
# static int    n_rows = 0;
# 
# /* ── detection ── */
# typedef struct {
#     int start_idx, end_idx;
#     double gx_mean, gx_min, gx_integral_deg, az_mean;
#     int rule;
# } DetectionWindow;
# 
# static DetectionWindow detections[MAX_DETECTIONS];
# static int n_detections = 0;
# 
# /* ── merged event ── */
# typedef struct {
#     int    start_idx, end_idx;
#     double peak_negative_gx;
#     double mean_gx;
#     double integrated_rotation_deg;
# } Event;
# 
# static Event events[MAX_EVENTS];
# static int   n_events = 0;
# 
# /* ── column indices ── */
# static int col_gx=-1, col_az=-1, col_ts=-1;
# 
# /* ════════════════════════════════════════
#    CSV helpers
#    ════════════════════════════════════════ */
# void clean_token(char *s){
#     int i=0; while(s[i]==' '||s[i]=='"') i++;
#     memmove(s,s+i,strlen(s+i)+1);
#     int len=(int)strlen(s);
#     while(len>0&&(s[len-1]==' '||s[len-1]=='"'||
#           s[len-1]=='\n'||s[len-1]=='\r')) s[--len]='\0';
# }
# void normalize(const char *src,char *dst,int maxlen){
#     int j=0;
#     for(int i=0;src[i]&&j<maxlen-1;i++){
#         char c=src[i]; if(c>='A'&&c<='Z') c+=32;
#         if(c==' '||c=='_'||c=='-'||c=='('||c==')'||c=='/') continue;
#         dst[j++]=c;
#     } dst[j]='\0';
# }
# int split_csv(char *line,char tokens[][MAX_COL_LEN],int max_tokens){
#     int count=0; char *p=line;
#     while(count<max_tokens){
#         char *start=p; while(*p&&*p!=',') p++;
#         int len=(int)(p-start); if(len>=MAX_COL_LEN) len=MAX_COL_LEN-1;
#         strncpy(tokens[count],start,len); tokens[count][len]='\0';
#         clean_token(tokens[count]); count++;
#         if(*p==',') p++; else break;
#     } return count;
# }
# int parse_header(char *line){
#     char tokens[MAX_COLS][MAX_COL_LEN];
#     int n=split_csv(line,tokens,MAX_COLS);
#     col_ts=col_gx=col_az=-1;
#     for(int i=0;i<n;i++){
#         char norm[MAX_COL_LEN]; normalize(tokens[i],norm,MAX_COL_LEN);
#         if(col_ts<0&&(strcmp(norm,"timestamp")==0||strcmp(norm,"time")==0||
#            strcmp(norm,"datetime")==0)) col_ts=i;
#         if(col_gx<0&&(strcmp(norm,"gxdps")==0||strcmp(norm,"gx")==0||
#            strcmp(norm,"gyrox")==0||strcmp(norm,"gyroxdps")==0)) col_gx=i;
#         if(col_az<0&&(strcmp(norm,"azg")==0||strcmp(norm,"az")==0||
#            strcmp(norm,"accz")==0||strcmp(norm,"accelz")==0)) col_az=i;
#     }
#     return (col_gx>=0&&col_az>=0)?0:-1;
# }
# int load_csv(const char *path){
#     FILE *f=fopen(path,"r"); if(!f){perror("fopen");return -1;}
#     char line[MAX_LINE_LEN];
#     if(!fgets(line,sizeof(line),f)){fclose(f);return -1;}
#     if(parse_header(line)!=0){fprintf(stderr,"Cols not found\n");fclose(f);return -1;}
#     n_rows=0;
#     while(fgets(line,sizeof(line),f)&&n_rows<MAX_ROWS){
#         char tokens[MAX_COLS][MAX_COL_LEN];
#         int n=split_csv(line,tokens,MAX_COLS);
#         if(n<=col_gx||n<=col_az) continue;
#         char *ep;
#         double gv=strtod(tokens[col_gx],&ep); if(ep==tokens[col_gx]) continue;
#         double av=strtod(tokens[col_az],&ep); if(ep==tokens[col_az]) continue;
#         gx_raw[n_rows]=gv; az_raw[n_rows]=av;
#         if(col_ts>=0&&n>col_ts) strncpy(timestamps[n_rows],tokens[col_ts],31);
#         else snprintf(timestamps[n_rows],31,"row_%d",n_rows);
#         n_rows++;
#     }
#     fclose(f); return n_rows;
# }
# 
# /* ════════════════════════════════════════
#    Moving average + dt estimate
#    ════════════════════════════════════════ */
# void moving_average(const double *in,double *out,int n,int k){
#     for(int i=0;i<n;i++){
#         int start=i-k+1; if(start<0) start=0;
#         int count=i-start+1; double sum=0.0;
#         for(int j=start;j<=i;j++) sum+=in[j];
#         out[i]=sum/count;
#     }
# }
# double estimate_dt(void){
#     double diffs[MAX_ROWS]; int nd=0;
#     for(int i=1;i<n_rows;i++){
#         const char *a=timestamps[i-1],*b=timestamps[i];
#         int cc=0,pa=-1,pb=-1;
#         for(int k=0;a[k];k++) if(a[k]==':'){cc++;if(cc==2){pa=k+1;break;}}
#         cc=0;
#         for(int k=0;b[k];k++) if(b[k]==':'){cc++;if(cc==2){pb=k+1;break;}}
#         if(pa<0||pb<0) continue;
#         int mpa=-1,mpb=-1; cc=0;
#         for(int k=0;a[k];k++) if(a[k]==':'){cc++;if(cc==1){mpa=k+1;break;}}
#         cc=0;
#         for(int k=0;b[k];k++) if(b[k]==':'){cc++;if(cc==1){mpb=k+1;break;}}
#         double ta=strtod(a+mpa,NULL)*60+strtod(a+pa,NULL);
#         double tb=strtod(b+mpb,NULL)*60+strtod(b+pb,NULL);
#         double diff=tb-ta;
#         if(diff>0&&diff<2.0) diffs[nd++]=diff;
#     }
#     if(nd==0) return DEFAULT_DT;
#     for(int i=1;i<nd;i++){
#         double key=diffs[i]; int j=i-1;
#         while(j>=0&&diffs[j]>key){diffs[j+1]=diffs[j];j--;}
#         diffs[j+1]=key;
#     }
#     return diffs[nd/2];
# }
# 
# /* ════════════════════════════════════════
#    Detection
#    ════════════════════════════════════════ */
# void detect_left_turn_windows(double dt){
#     n_detections=0;
#     if(n_rows<WINDOW_SIZE) return;
#     for(int start=0;start<=n_rows-WINDOW_SIZE;start++){
#         int end=start+WINDOW_SIZE-1;
#         double gx_mean=0,gx_min=gx_s[start],gx_sum=0,az_mean=0;
#         for(int i=start;i<=end;i++){
#             gx_sum+=gx_s[i]; az_mean+=az_s[i];
#             if(gx_s[i]<gx_min) gx_min=gx_s[i];
#         }
#         gx_mean=gx_sum/WINDOW_SIZE;
#         az_mean=az_mean/WINDOW_SIZE;
#         double gx_integral=gx_sum*dt;
#         int strict=(gx_mean<STRICT_GX_MEAN&&gx_min<STRICT_GX_MIN&&gx_integral<STRICT_GX_INT);
#         int relaxed=(gx_mean<RELAX_GX_MEAN&&gx_min<RELAX_GX_MIN&&gx_integral<RELAX_GX_INT&&az_mean<RELAX_AZ_MEAN);
#         if((strict||relaxed)&&n_detections<MAX_DETECTIONS){
#             detections[n_detections].start_idx=start;
#             detections[n_detections].end_idx=end;
#             detections[n_detections].gx_mean=gx_mean;
#             detections[n_detections].gx_min=gx_min;
#             detections[n_detections].gx_integral_deg=gx_integral;
#             detections[n_detections].az_mean=az_mean;
#             detections[n_detections].rule=strict?0:1;
#             n_detections++;
#         }
#     }
# }
# 
# /* ════════════════════════════════════════
#    Build a single event from index range
#    ════════════════════════════════════════ */
# void build_event(int start_idx, int end_idx, Event *ev){
#     ev->start_idx = start_idx;
#     ev->end_idx   = end_idx;
#     double peak = gx_raw[start_idx];
#     double sum  = 0.0;
#     for(int i = start_idx; i <= end_idx; i++){
#         if(gx_raw[i] < peak) peak = gx_raw[i];
#         sum += gx_raw[i];
#     }
#     ev->peak_negative_gx       = peak;
#     ev->mean_gx                = sum / (end_idx - start_idx + 1);
#     ev->integrated_rotation_deg = sum * estimate_dt();
# }
# 
# /* ════════════════════════════════════════
#    Merge overlapping/nearby detections
#    Mirrors Python merge_detection_windows()
#    ════════════════════════════════════════ */
# void merge_detection_windows(double dt){
#     n_events = 0;
#     if(n_detections == 0) return;
# 
#     int cur_start = detections[0].start_idx;
#     int cur_end   = detections[0].end_idx;
# 
#     for(int i = 1; i < n_detections; i++){
#         if(detections[i].start_idx <= cur_end + MERGE_GAP){
#             /* extend current event */
#             if(detections[i].end_idx > cur_end)
#                 cur_end = detections[i].end_idx;
#         } else {
#             /* save finished event */
#             build_event(cur_start, cur_end, &events[n_events++]);
#             cur_start = detections[i].start_idx;
#             cur_end   = detections[i].end_idx;
#         }
#     }
#     /* save last event */
#     build_event(cur_start, cur_end, &events[n_events++]);
#     (void)dt;
# }
# 
# /* ════════════════════════════════════════
#    MAIN — Step 4 test
#    ════════════════════════════════════════ */
# int main(void){
#     const char *csv_path = "imu_6axis_data_20260308_084155_Trip2_Left.csv";
# 
#     printf("=== Step 4: Merge Detections into Events ===\n\n");
# 
#     if(load_csv(csv_path) < 0) return 1;
#     printf("Loaded %d rows.\n", n_rows);
# 
#     moving_average(gx_raw, gx_s, n_rows, SMOOTH_K);
#     moving_average(az_raw, az_s, n_rows, SMOOTH_K);
# 
#     double dt = estimate_dt();
#     printf("dt = %.4f s\n\n", dt);
# 
#     detect_left_turn_windows(dt);
#     printf("Triggered windows : %d\n", n_detections);
# 
#     merge_detection_windows(dt);
#     printf("Merged events     : %d  (Python = 6)\n\n", n_events);
# 
#     /* ── summary table ── */
#     printf("%-6s %-9s %-8s %-15s %-15s %-12s %-10s %-10s %-12s\n",
#            "Event","StartIdx","EndIdx",
#            "StartTime","EndTime",
#            "Duration(s)","PeakNegGX","MeanGX","IntRot(deg)");
#     printf("%-6s %-9s %-8s %-15s %-15s %-12s %-10s %-10s %-12s\n",
#            "------","---------","--------",
#            "---------------","---------------",
#            "------------","----------","----------","------------");
# 
#     for(int i = 0; i < n_events; i++){
#         Event *ev = &events[i];
#         double duration = (ev->end_idx - ev->start_idx + 1) * dt;
# 
#         /* extract HH:MM:SS from timestamps */
#         char t_start[20], t_end[20];
#         strncpy(t_start, timestamps[ev->start_idx], 19); t_start[19]='\0';
#         strncpy(t_end,   timestamps[ev->end_idx],   19); t_end[19]='\0';
# 
#         printf("%-6d %-9d %-8d %-15s %-15s %-12.2f %-10.2f %-10.2f %-12.2f\n",
#                i+1,
#                ev->start_idx, ev->end_idx,
#                t_start, t_end,
#                duration,
#                ev->peak_negative_gx,
#                ev->mean_gx,
#                ev->integrated_rotation_deg);
#     }
# 
#     return 0;
# }

!gcc step4_merge_events.c -o step4 -lm
!./step4





"""## Step 5 — Full Summary + Save Output CSV

**What it does:** Prints the complete detection summary (matching Python's console output)
and saves results to `detected_left_turn_events.csv`.

**Expected output:** 6 events with identical indices, timestamps, and values to Python.

### ⚠️ Watch Out For:
- The output CSV is saved in the **current working directory** (inside `/content/sensor/` in Colab).
  To download it: right-click the file in the Colab file browser → Download.
- All 6 event values (StartIdx, EndIdx, Duration, PeakNegGX, MeanGX, IntRot) should
  match the Python output exactly. If any differ, check the `estimate_dt()` result first.

### ✅ Validation Checkpoint:
At this point, the C code is a **fully verified equivalent** of the Python code.
Steps 6 and 7 extend it with right-turn detection and real-time streaming.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile step5_output.c
# #include <stdio.h>
# #include <stdlib.h>
# #include <string.h>
# 
# #define MAX_ROWS       5000
# #define MAX_COLS         20
# #define MAX_COL_LEN      64
# #define MAX_LINE_LEN    512
# #define MAX_DETECTIONS 5000
# #define MAX_EVENTS      500
# 
# #define WINDOW_SIZE    40
# #define SMOOTH_K        5
# #define DEFAULT_DT   0.102
# #define MERGE_GAP      10
# 
# #define STRICT_GX_MEAN  -4.0
# #define STRICT_GX_MIN  -12.0
# #define STRICT_GX_INT  -15.0
# #define RELAX_GX_MEAN   -3.0
# #define RELAX_GX_MIN   -10.0
# #define RELAX_GX_INT   -12.0
# #define RELAX_AZ_MEAN   -0.03
# 
# /* ── data ── */
# static double gx_raw[MAX_ROWS], az_raw[MAX_ROWS];
# static double gx_s  [MAX_ROWS], az_s  [MAX_ROWS];
# static char   timestamps[MAX_ROWS][32];
# static int    n_rows = 0;
# static double g_dt   = DEFAULT_DT;
# 
# typedef struct {
#     int start_idx, end_idx;
#     double gx_mean, gx_min, gx_integral_deg, az_mean;
#     int rule;
# } DetectionWindow;
# 
# typedef struct {
#     int    start_idx, end_idx;
#     double peak_negative_gx;
#     double mean_gx;
#     double integrated_rotation_deg;
# } Event;
# 
# static DetectionWindow detections[MAX_DETECTIONS];
# static int n_detections = 0;
# static Event events[MAX_EVENTS];
# static int   n_events = 0;
# 
# static int col_gx=-1, col_az=-1, col_ts=-1;
# 
# /* ════════════════════════════════════════
#    CSV helpers
#    ════════════════════════════════════════ */
# void clean_token(char *s){
#     int i=0; while(s[i]==' '||s[i]=='"') i++;
#     memmove(s,s+i,strlen(s+i)+1);
#     int len=(int)strlen(s);
#     while(len>0&&(s[len-1]==' '||s[len-1]=='"'||
#           s[len-1]=='\n'||s[len-1]=='\r')) s[--len]='\0';
# }
# void normalize(const char *src,char *dst,int maxlen){
#     int j=0;
#     for(int i=0;src[i]&&j<maxlen-1;i++){
#         char c=src[i]; if(c>='A'&&c<='Z') c+=32;
#         if(c==' '||c=='_'||c=='-'||c=='('||c==')'||c=='/') continue;
#         dst[j++]=c;
#     } dst[j]='\0';
# }
# int split_csv(char *line,char tokens[][MAX_COL_LEN],int max_tokens){
#     int count=0; char *p=line;
#     while(count<max_tokens){
#         char *start=p; while(*p&&*p!=',') p++;
#         int len=(int)(p-start); if(len>=MAX_COL_LEN) len=MAX_COL_LEN-1;
#         strncpy(tokens[count],start,len); tokens[count][len]='\0';
#         clean_token(tokens[count]); count++;
#         if(*p==',') p++; else break;
#     } return count;
# }
# int parse_header(char *line){
#     char tokens[MAX_COLS][MAX_COL_LEN];
#     int n=split_csv(line,tokens,MAX_COLS);
#     col_ts=col_gx=col_az=-1;
#     for(int i=0;i<n;i++){
#         char norm[MAX_COL_LEN]; normalize(tokens[i],norm,MAX_COL_LEN);
#         if(col_ts<0&&(strcmp(norm,"timestamp")==0||strcmp(norm,"time")==0||
#            strcmp(norm,"datetime")==0)) col_ts=i;
#         if(col_gx<0&&(strcmp(norm,"gxdps")==0||strcmp(norm,"gx")==0||
#            strcmp(norm,"gyrox")==0||strcmp(norm,"gyroxdps")==0)) col_gx=i;
#         if(col_az<0&&(strcmp(norm,"azg")==0||strcmp(norm,"az")==0||
#            strcmp(norm,"accz")==0||strcmp(norm,"accelz")==0)) col_az=i;
#     }
#     return (col_gx>=0&&col_az>=0)?0:-1;
# }
# int load_csv(const char *path){
#     FILE *f=fopen(path,"r"); if(!f){perror("fopen");return -1;}
#     char line[MAX_LINE_LEN];
#     if(!fgets(line,sizeof(line),f)){fclose(f);return -1;}
#     if(parse_header(line)!=0){fprintf(stderr,"Cols not found\n");fclose(f);return -1;}
#     n_rows=0;
#     while(fgets(line,sizeof(line),f)&&n_rows<MAX_ROWS){
#         char tokens[MAX_COLS][MAX_COL_LEN];
#         int n=split_csv(line,tokens,MAX_COLS);
#         if(n<=col_gx||n<=col_az) continue;
#         char *ep;
#         double gv=strtod(tokens[col_gx],&ep); if(ep==tokens[col_gx]) continue;
#         double av=strtod(tokens[col_az],&ep); if(ep==tokens[col_az]) continue;
#         gx_raw[n_rows]=gv; az_raw[n_rows]=av;
#         if(col_ts>=0&&n>col_ts) strncpy(timestamps[n_rows],tokens[col_ts],31);
#         else snprintf(timestamps[n_rows],31,"row_%d",n_rows);
#         n_rows++;
#     }
#     fclose(f); return n_rows;
# }
# 
# /* ════════════════════════════════════════
#    Moving average + dt
#    ════════════════════════════════════════ */
# void moving_average(const double *in,double *out,int n,int k){
#     for(int i=0;i<n;i++){
#         int start=i-k+1; if(start<0) start=0;
#         int count=i-start+1; double sum=0.0;
#         for(int j=start;j<=i;j++) sum+=in[j];
#         out[i]=sum/count;
#     }
# }
# double estimate_dt(void){
#     double diffs[MAX_ROWS]; int nd=0;
#     for(int i=1;i<n_rows;i++){
#         const char *a=timestamps[i-1],*b=timestamps[i];
#         int cc=0,pa=-1,pb=-1;
#         for(int k=0;a[k];k++) if(a[k]==':'){cc++;if(cc==2){pa=k+1;break;}}
#         cc=0;
#         for(int k=0;b[k];k++) if(b[k]==':'){cc++;if(cc==2){pb=k+1;break;}}
#         if(pa<0||pb<0) continue;
#         int mpa=-1,mpb=-1; cc=0;
#         for(int k=0;a[k];k++) if(a[k]==':'){cc++;if(cc==1){mpa=k+1;break;}}
#         cc=0;
#         for(int k=0;b[k];k++) if(b[k]==':'){cc++;if(cc==1){mpb=k+1;break;}}
#         double ta=strtod(a+mpa,NULL)*60+strtod(a+pa,NULL);
#         double tb=strtod(b+mpb,NULL)*60+strtod(b+pb,NULL);
#         double diff=tb-ta;
#         if(diff>0&&diff<2.0) diffs[nd++]=diff;
#     }
#     if(nd==0) return DEFAULT_DT;
#     for(int i=1;i<nd;i++){
#         double key=diffs[i]; int j=i-1;
#         while(j>=0&&diffs[j]>key){diffs[j+1]=diffs[j];j--;}
#         diffs[j+1]=key;
#     }
#     return diffs[nd/2];
# }
# 
# /* ════════════════════════════════════════
#    Detection + merge
#    ════════════════════════════════════════ */
# void detect_left_turn_windows(void){
#     n_detections=0;
#     if(n_rows<WINDOW_SIZE) return;
#     for(int start=0;start<=n_rows-WINDOW_SIZE;start++){
#         int end=start+WINDOW_SIZE-1;
#         double gx_mean=0,gx_min=gx_s[start],gx_sum=0,az_mean=0;
#         for(int i=start;i<=end;i++){
#             gx_sum+=gx_s[i]; az_mean+=az_s[i];
#             if(gx_s[i]<gx_min) gx_min=gx_s[i];
#         }
#         gx_mean=gx_sum/WINDOW_SIZE; az_mean/=WINDOW_SIZE;
#         double gx_integral=gx_sum*g_dt;
#         int strict=(gx_mean<STRICT_GX_MEAN&&gx_min<STRICT_GX_MIN&&gx_integral<STRICT_GX_INT);
#         int relaxed=(gx_mean<RELAX_GX_MEAN&&gx_min<RELAX_GX_MIN&&gx_integral<RELAX_GX_INT&&az_mean<RELAX_AZ_MEAN);
#         if((strict||relaxed)&&n_detections<MAX_DETECTIONS){
#             detections[n_detections].start_idx=start;
#             detections[n_detections].end_idx=end;
#             detections[n_detections].gx_mean=gx_mean;
#             detections[n_detections].gx_min=gx_min;
#             detections[n_detections].gx_integral_deg=gx_integral;
#             detections[n_detections].az_mean=az_mean;
#             detections[n_detections].rule=strict?0:1;
#             n_detections++;
#         }
#     }
# }
# 
# void build_event(int s,int e,Event *ev){
#     ev->start_idx=s; ev->end_idx=e;
#     double peak=gx_raw[s],sum=0.0;
#     for(int i=s;i<=e;i++){
#         if(gx_raw[i]<peak) peak=gx_raw[i];
#         sum+=gx_raw[i];
#     }
#     ev->peak_negative_gx=peak;
#     ev->mean_gx=sum/(e-s+1);
#     ev->integrated_rotation_deg=sum*g_dt;
# }
# 
# void merge_events(void){
#     n_events=0; if(n_detections==0) return;
#     int cs=detections[0].start_idx, ce=detections[0].end_idx;
#     for(int i=1;i<n_detections;i++){
#         if(detections[i].start_idx<=ce+MERGE_GAP){
#             if(detections[i].end_idx>ce) ce=detections[i].end_idx;
#         } else {
#             build_event(cs,ce,&events[n_events++]);
#             cs=detections[i].start_idx; ce=detections[i].end_idx;
#         }
#     }
#     build_event(cs,ce,&events[n_events++]);
# }
# 
# /* ════════════════════════════════════════
#    Print summary — mirrors Python print_summary()
#    ════════════════════════════════════════ */
# void print_summary(void){
#     printf("\n==============================\n");
#     printf("Left Turn Detection Summary\n");
#     printf("==============================\n");
#     printf("Total samples           : %d\n",   n_rows);
#     printf("Estimated sample period : %.4f s\n", g_dt);
#     printf("Window duration         : %.3f s\n", WINDOW_SIZE * g_dt);
#     printf("Triggered windows       : %d\n",   n_detections);
#     printf("Detected events         : %d\n",   n_events);
# 
#     if(n_events == 0){ printf("\nNo left-turn events detected.\n"); return; }
# 
#     printf("\nDetected events:\n\n");
#     printf("%-6s %-9s %-8s %-26s %-26s %-12s %-10s %-10s %-12s\n",
#            "Event","StartIdx","EndIdx",
#            "StartTime","EndTime",
#            "Duration(s)","PeakNegGX","MeanGX","IntRot(deg)");
#     printf("%-6s %-9s %-8s %-26s %-26s %-12s %-10s %-10s %-12s\n",
#            "------","---------","--------",
#            "--------------------------","--------------------------",
#            "------------","----------","----------","------------");
# 
#     for(int i=0;i<n_events;i++){
#         Event *ev=&events[i];
#         double dur=(ev->end_idx - ev->start_idx + 1)*g_dt;
#         printf("%-6d %-9d %-8d %-26s %-26s %-12.2f %-10.2f %-10.2f %-12.2f\n",
#                i+1, ev->start_idx, ev->end_idx,
#                timestamps[ev->start_idx], timestamps[ev->end_idx],
#                dur,
#                ev->peak_negative_gx, ev->mean_gx,
#                ev->integrated_rotation_deg);
#     }
# }
# 
# /* ════════════════════════════════════════
#    Save output CSV — mirrors Python save_event_csv()
#    ════════════════════════════════════════ */
# void save_event_csv(const char *out_path){
#     FILE *f=fopen(out_path,"w");
#     if(!f){ perror("fopen output"); return; }
# 
#     /* header */
#     fprintf(f,"event_id,start_idx,end_idx,start_time,end_time,"
#               "duration_sec,peak_negative_gx_dps,mean_gx_dps,"
#               "integrated_rotation_deg\n");
# 
#     for(int i=0;i<n_events;i++){
#         Event *ev=&events[i];
#         double dur=(ev->end_idx - ev->start_idx + 1)*g_dt;
#         fprintf(f,"%d,%d,%d,%s,%s,%.4f,%.4f,%.4f,%.4f\n",
#                 i+1,
#                 ev->start_idx, ev->end_idx,
#                 timestamps[ev->start_idx], timestamps[ev->end_idx],
#                 dur,
#                 ev->peak_negative_gx, ev->mean_gx,
#                 ev->integrated_rotation_deg);
#     }
#     fclose(f);
#     printf("\nSaved event summary to: %s\n", out_path);
# }
# 
# /* ════════════════════════════════════════
#    MAIN
#    ════════════════════════════════════════ */
# int main(void){
#     const char *csv_in  = "imu_6axis_data_20260308_084155_Trip2_Left.csv";
#     const char *csv_out = "detected_left_turn_events.csv";
# 
#     printf("=== Step 5: Full Summary + CSV Output ===\n");
# 
#     if(load_csv(csv_in) < 0) return 1;
# 
#     moving_average(gx_raw, gx_s, n_rows, SMOOTH_K);
#     moving_average(az_raw, az_s, n_rows, SMOOTH_K);
# 
#     g_dt = estimate_dt();
# 
#     detect_left_turn_windows();
#     merge_events();
# 
#     print_summary();
#     save_event_csv(csv_out);
# 
#     /* verify output CSV was written */
#     printf("\n--- Output CSV preview ---\n");
#     FILE *f=fopen(csv_out,"r");
#     if(f){
#         char line[512];
#         int lines=0;
#         while(fgets(line,sizeof(line),f)&&lines<8){
#             printf("%s", line); lines++;
#         }
#         fclose(f);
#     }
# 
#     return 0;
# }

!gcc step5_output.c -o step5 -lm
!./step5





"""## Step 6 — Left + Right Turn Detection with Notifications

**What it does:** Runs detection for **both directions** simultaneously.
Right-turn thresholds are the mirror image of left-turn thresholds (all signs flipped).
Events are sorted chronologically and printed as turn-by-turn notifications.

**Expected output:** 6 left turns + 3 right turns = 9 total notifications.

### ⚠️ Watch Out For:
- Right-turn thresholds assume the same sensor orientation as left turns. If your
  IMU is mounted differently, the axis and sign conventions will change.
- The 3 right turns detected in a "Left Trip" CSV are **real** — they represent
  straightening maneuvers and lane corrections between left turns.
- If you get unexpected right turns, increase `R_STRICT_GX_MEAN` threshold.

### 🔩 Hardware Note:
Both detectors run **in parallel on the same window** — no extra memory needed.
On Arduino, both checks happen inside the same ISR (interrupt service routine) or loop cycle.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile step6_both_turns.c
# #include <stdio.h>
# #include <stdlib.h>
# #include <string.h>
# 
# #define MAX_ROWS       5000
# #define MAX_COLS         20
# #define MAX_COL_LEN      64
# #define MAX_LINE_LEN    512
# #define MAX_DETECTIONS 5000
# #define MAX_EVENTS      500
# 
# #define WINDOW_SIZE    40
# #define SMOOTH_K        5
# #define DEFAULT_DT   0.102
# #define MERGE_GAP      10
# 
# /* ── LEFT turn thresholds (gx negative) ── */
# #define L_STRICT_GX_MEAN  -4.0
# #define L_STRICT_GX_MIN  -12.0
# #define L_STRICT_GX_INT  -15.0
# #define L_RELAX_GX_MEAN   -3.0
# #define L_RELAX_GX_MIN   -10.0
# #define L_RELAX_GX_INT   -12.0
# #define L_RELAX_AZ_MEAN   -0.03
# 
# /* ── RIGHT turn thresholds (gx positive, mirror of left) ── */
# #define R_STRICT_GX_MEAN  4.0
# #define R_STRICT_GX_MAX  12.0
# #define R_STRICT_GX_INT  15.0
# #define R_RELAX_GX_MEAN   3.0
# #define R_RELAX_GX_MAX   10.0
# #define R_RELAX_GX_INT   12.0
# #define R_RELAX_AZ_MEAN   0.03
# 
# /* ── data ── */
# static double gx_raw[MAX_ROWS], az_raw[MAX_ROWS];
# static double gx_s  [MAX_ROWS], az_s  [MAX_ROWS];
# static char   timestamps[MAX_ROWS][32];
# static int    n_rows = 0;
# static double g_dt   = DEFAULT_DT;
# 
# /* ── turn direction labels ── */
# #define TURN_LEFT  0
# #define TURN_RIGHT 1
# 
# typedef struct {
#     int    start_idx, end_idx;
#     double peak_gx;           /* most negative (left) or most positive (right) */
#     double mean_gx;
#     double integrated_rotation_deg;
#     int    direction;         /* TURN_LEFT or TURN_RIGHT */
# } Event;
# 
# static Event left_events [MAX_EVENTS];
# static int   n_left  = 0;
# static Event right_events[MAX_EVENTS];
# static int   n_right = 0;
# 
# /* unified sorted list for timeline printing */
# static Event all_events[MAX_EVENTS * 2];
# static int   n_all = 0;
# 
# static int col_gx=-1, col_az=-1, col_ts=-1;
# 
# /* ════════════════════════════════════════
#    CSV helpers
#    ════════════════════════════════════════ */
# void clean_token(char *s){
#     int i=0; while(s[i]==' '||s[i]=='"') i++;
#     memmove(s,s+i,strlen(s+i)+1);
#     int len=(int)strlen(s);
#     while(len>0&&(s[len-1]==' '||s[len-1]=='"'||
#           s[len-1]=='\n'||s[len-1]=='\r')) s[--len]='\0';
# }
# void normalize(const char *src,char *dst,int maxlen){
#     int j=0;
#     for(int i=0;src[i]&&j<maxlen-1;i++){
#         char c=src[i]; if(c>='A'&&c<='Z') c+=32;
#         if(c==' '||c=='_'||c=='-'||c=='('||c==')'||c=='/') continue;
#         dst[j++]=c;
#     } dst[j]='\0';
# }
# int split_csv(char *line,char tokens[][MAX_COL_LEN],int max_tokens){
#     int count=0; char *p=line;
#     while(count<max_tokens){
#         char *start=p; while(*p&&*p!=',') p++;
#         int len=(int)(p-start); if(len>=MAX_COL_LEN) len=MAX_COL_LEN-1;
#         strncpy(tokens[count],start,len); tokens[count][len]='\0';
#         clean_token(tokens[count]); count++;
#         if(*p==',') p++; else break;
#     } return count;
# }
# int parse_header(char *line){
#     char tokens[MAX_COLS][MAX_COL_LEN];
#     int n=split_csv(line,tokens,MAX_COLS);
#     col_ts=col_gx=col_az=-1;
#     for(int i=0;i<n;i++){
#         char norm[MAX_COL_LEN]; normalize(tokens[i],norm,MAX_COL_LEN);
#         if(col_ts<0&&(strcmp(norm,"timestamp")==0||strcmp(norm,"time")==0||
#            strcmp(norm,"datetime")==0)) col_ts=i;
#         if(col_gx<0&&(strcmp(norm,"gxdps")==0||strcmp(norm,"gx")==0||
#            strcmp(norm,"gyrox")==0||strcmp(norm,"gyroxdps")==0)) col_gx=i;
#         if(col_az<0&&(strcmp(norm,"azg")==0||strcmp(norm,"az")==0||
#            strcmp(norm,"accz")==0||strcmp(norm,"accelz")==0)) col_az=i;
#     }
#     return (col_gx>=0&&col_az>=0)?0:-1;
# }
# int load_csv(const char *path){
#     FILE *f=fopen(path,"r"); if(!f){perror("fopen");return -1;}
#     char line[MAX_LINE_LEN];
#     if(!fgets(line,sizeof(line),f)){fclose(f);return -1;}
#     if(parse_header(line)!=0){
#         fprintf(stderr,"Required columns not found.\n");
#         fclose(f);return -1;
#     }
#     n_rows=0;
#     while(fgets(line,sizeof(line),f)&&n_rows<MAX_ROWS){
#         char tokens[MAX_COLS][MAX_COL_LEN];
#         int n=split_csv(line,tokens,MAX_COLS);
#         if(n<=col_gx||n<=col_az) continue;
#         char *ep;
#         double gv=strtod(tokens[col_gx],&ep); if(ep==tokens[col_gx]) continue;
#         double av=strtod(tokens[col_az],&ep); if(ep==tokens[col_az]) continue;
#         gx_raw[n_rows]=gv; az_raw[n_rows]=av;
#         if(col_ts>=0&&n>col_ts) strncpy(timestamps[n_rows],tokens[col_ts],31);
#         else snprintf(timestamps[n_rows],31,"row_%d",n_rows);
#         n_rows++;
#     }
#     fclose(f); return n_rows;
# }
# 
# /* ════════════════════════════════════════
#    Utilities
#    ════════════════════════════════════════ */
# void moving_average(const double *in,double *out,int n,int k){
#     for(int i=0;i<n;i++){
#         int start=i-k+1; if(start<0) start=0;
#         int count=i-start+1; double sum=0.0;
#         for(int j=start;j<=i;j++) sum+=in[j];
#         out[i]=sum/count;
#     }
# }
# double estimate_dt(void){
#     double diffs[MAX_ROWS]; int nd=0;
#     for(int i=1;i<n_rows;i++){
#         const char *a=timestamps[i-1],*b=timestamps[i];
#         int cc=0,pa=-1,pb=-1;
#         for(int k=0;a[k];k++) if(a[k]==':'){cc++;if(cc==2){pa=k+1;break;}}
#         cc=0;
#         for(int k=0;b[k];k++) if(b[k]==':'){cc++;if(cc==2){pb=k+1;break;}}
#         if(pa<0||pb<0) continue;
#         int mpa=-1,mpb=-1; cc=0;
#         for(int k=0;a[k];k++) if(a[k]==':'){cc++;if(cc==1){mpa=k+1;break;}}
#         cc=0;
#         for(int k=0;b[k];k++) if(b[k]==':'){cc++;if(cc==1){mpb=k+1;break;}}
#         double ta=strtod(a+mpa,NULL)*60+strtod(a+pa,NULL);
#         double tb=strtod(b+mpb,NULL)*60+strtod(b+pb,NULL);
#         double diff=tb-ta;
#         if(diff>0&&diff<2.0) diffs[nd++]=diff;
#     }
#     if(nd==0) return DEFAULT_DT;
#     for(int i=1;i<nd;i++){
#         double key=diffs[i]; int j=i-1;
#         while(j>=0&&diffs[j]>key){diffs[j+1]=diffs[j];j--;}
#         diffs[j+1]=key;
#     }
#     return diffs[nd/2];
# }
# 
# /* ════════════════════════════════════════
#    Build event from raw gx segment
#    ════════════════════════════════════════ */
# void build_event(int s, int e, int direction, Event *ev){
#     ev->start_idx = s;
#     ev->end_idx   = e;
#     ev->direction = direction;
#     double peak = gx_raw[s], sum = 0.0;
#     for(int i=s;i<=e;i++){
#         sum += gx_raw[i];
#         if(direction == TURN_LEFT  && gx_raw[i] < peak) peak = gx_raw[i];
#         if(direction == TURN_RIGHT && gx_raw[i] > peak) peak = gx_raw[i];
#     }
#     ev->peak_gx                 = peak;
#     ev->mean_gx                 = sum / (e - s + 1);
#     ev->integrated_rotation_deg = sum * g_dt;
# }
# 
# /* ════════════════════════════════════════
#    Generic detector + merger
#    dir = TURN_LEFT or TURN_RIGHT
#    ════════════════════════════════════════ */
# void detect_and_merge(int direction, Event *out_events, int *out_count){
#     /* local detection list */
#     static int det_start[MAX_DETECTIONS];
#     static int det_end  [MAX_DETECTIONS];
#     int nd = 0;
# 
#     for(int start=0; start<=n_rows-WINDOW_SIZE; start++){
#         int end = start + WINDOW_SIZE - 1;
#         double gx_mean=0, gx_ext=gx_s[start], gx_sum=0, az_mean=0;
# 
#         for(int i=start;i<=end;i++){
#             gx_sum  += gx_s[i];
#             az_mean += az_s[i];
#             if(direction==TURN_LEFT  && gx_s[i] < gx_ext) gx_ext=gx_s[i];
#             if(direction==TURN_RIGHT && gx_s[i] > gx_ext) gx_ext=gx_s[i];
#         }
#         gx_mean  = gx_sum / WINDOW_SIZE;
#         az_mean /= WINDOW_SIZE;
#         double gx_integral = gx_sum * g_dt;
# 
#         int fires = 0;
#         if(direction == TURN_LEFT){
#             int strict  = (gx_mean<L_STRICT_GX_MEAN &&
#                            gx_ext <L_STRICT_GX_MIN  &&
#                            gx_integral<L_STRICT_GX_INT);
#             int relaxed = (gx_mean<L_RELAX_GX_MEAN  &&
#                            gx_ext <L_RELAX_GX_MIN   &&
#                            gx_integral<L_RELAX_GX_INT &&
#                            az_mean<L_RELAX_AZ_MEAN);
#             fires = strict || relaxed;
#         } else {
#             /* right turn: all signs flipped */
#             int strict  = (gx_mean>R_STRICT_GX_MEAN &&
#                            gx_ext >R_STRICT_GX_MAX  &&
#                            gx_integral>R_STRICT_GX_INT);
#             int relaxed = (gx_mean>R_RELAX_GX_MEAN  &&
#                            gx_ext >R_RELAX_GX_MAX   &&
#                            gx_integral>R_RELAX_GX_INT &&
#                            az_mean>R_RELAX_AZ_MEAN);
#             fires = strict || relaxed;
#         }
# 
#         if(fires && nd < MAX_DETECTIONS){
#             det_start[nd] = start;
#             det_end  [nd] = end;
#             nd++;
#         }
#     }
# 
#     /* merge */
#     *out_count = 0;
#     if(nd == 0) return;
# 
#     int cs = det_start[0], ce = det_end[0];
#     for(int i=1;i<nd;i++){
#         if(det_start[i] <= ce + MERGE_GAP){
#             if(det_end[i] > ce) ce = det_end[i];
#         } else {
#             build_event(cs, ce, direction, &out_events[(*out_count)++]);
#             cs = det_start[i]; ce = det_end[i];
#         }
#     }
#     build_event(cs, ce, direction, &out_events[(*out_count)++]);
# }
# 
# /* ════════════════════════════════════════
#    Notification printer
#    ════════════════════════════════════════ */
# void print_notification(const Event *ev, int id){
#     const char *dir_str = (ev->direction == TURN_LEFT)
#                           ? "LEFT  <<<" : "RIGHT >>>";
#     const char *arrow   = (ev->direction == TURN_LEFT)
#                           ? "<-- YOU ARE TURNING LEFT"
#                           : "--> YOU ARE TURNING RIGHT";
# 
#     printf("\n╔══════════════════════════════════════════╗\n");
#     printf("║  TURN NOTIFICATION  #%-3d                 ║\n", id);
#     printf("╠══════════════════════════════════════════╣\n");
#     printf("║  Direction  : %-28s║\n", dir_str);
#     printf("║  %-40s║\n", arrow);
#     printf("║  Start time : %-27s ║\n", timestamps[ev->start_idx]);
#     printf("║  End time   : %-27s ║\n", timestamps[ev->end_idx]);
#     printf("║  Duration   : %-5.2f s                      ║\n",
#            (ev->end_idx - ev->start_idx + 1) * g_dt);
#     printf("║  Peak GX    : %-8.2f dps                 ║\n", ev->peak_gx);
#     printf("║  Rotation   : %-8.2f deg                 ║\n",
#            ev->integrated_rotation_deg);
#     printf("╚══════════════════════════════════════════╝\n");
# }
# 
# /* sort all_events by start_idx */
# int cmp_events(const void *a, const void *b){
#     return ((Event*)a)->start_idx - ((Event*)b)->start_idx;
# }
# 
# /* ════════════════════════════════════════
#    MAIN
#    ════════════════════════════════════════ */
# int main(void){
#     const char *csv_path = "imu_6axis_data_20260308_084155_Trip2_Left.csv";
# 
#     printf("=== Step 6: Left + Right Turn Detection ===\n\n");
# 
#     if(load_csv(csv_path) < 0) return 1;
#     printf("Loaded %d rows.\n", n_rows);
# 
#     moving_average(gx_raw, gx_s, n_rows, SMOOTH_K);
#     moving_average(az_raw, az_s, n_rows, SMOOTH_K);
#     g_dt = estimate_dt();
#     printf("dt = %.4f s\n\n", g_dt);
# 
#     /* detect both directions */
#     detect_and_merge(TURN_LEFT,  left_events,  &n_left);
#     detect_and_merge(TURN_RIGHT, right_events, &n_right);
# 
#     printf("Left  turn events : %d\n", n_left);
#     printf("Right turn events : %d\n\n", n_right);
# 
#     /* merge into one timeline */
#     n_all = 0;
#     for(int i=0;i<n_left; i++) all_events[n_all++] = left_events[i];
#     for(int i=0;i<n_right;i++) all_events[n_all++] = right_events[i];
#     qsort(all_events, n_all, sizeof(Event), cmp_events);
# 
#     /* ── fire notifications in time order ── */
#     printf("========================================\n");
#     printf("  TURN-BY-TURN NOTIFICATIONS\n");
#     printf("========================================\n");
# 
#     for(int i=0;i<n_all;i++)
#         print_notification(&all_events[i], i+1);
# 
#     /* ── summary table ── */
#     printf("\n\n%-6s %-8s %-9s %-8s %-26s %-12s %-10s\n",
#            "Event","Dir","StartIdx","EndIdx","StartTime","Duration(s)","PeakGX");
#     printf("%-6s %-8s %-9s %-8s %-26s %-12s %-10s\n",
#            "------","--------","---------","--------",
#            "--------------------------","------------","----------");
#     for(int i=0;i<n_all;i++){
#         Event *ev=&all_events[i];
#         printf("%-6d %-8s %-9d %-8d %-26s %-12.2f %-10.2f\n",
#                i+1,
#                ev->direction==TURN_LEFT?"LEFT":"RIGHT",
#                ev->start_idx, ev->end_idx,
#                timestamps[ev->start_idx],
#                (ev->end_idx-ev->start_idx+1)*g_dt,
#                ev->peak_gx);
#     }
# 
#     return 0;
# }

!gcc step6_both_turns.c -o step6 -lm
!./step6





"""## Step 7 — Real-Time Streaming Simulation 🚨

**What it does:** Reads the CSV **one row at a time** with a 10ms delay between rows,
simulating a live 100Hz IMU sensor feed. Fires notifications **instantly** the moment
a turn is confirmed — without waiting for the full dataset.

**Expected output:** Notifications pop up mid-stream as the vehicle turns.
Progress ticks are printed every 100 rows.

### ⚠️ Watch Out For:
- `SIM_DELAY_MS = 10` simulates 100Hz. Set to `0` if you just want fast output without delay.
- The first 100 rows are pre-loaded to estimate `dt` — this is a one-time startup cost.
- Notifications fire **after** the MERGE_GAP timeout (10 samples ≈ 1 second after turn ends).
  This is the detection latency — unavoidable with a merging strategy.
- Row counter shows `[0 / ~1750]` during pre-load — this is normal, it resets after pre-load.

### 🔩 Deploying to Arduino / Raspberry Pi:
Replace the CSV streaming loop with **direct IMU sensor reads**:
- **Arduino:** Use `Wire.h` (I2C) or `SPI.h` to read MPU-6050 / ICM-42688 every 10ms
- **Raspberry Pi:** Use `smbus2` (Python) or `pigpio` (C) for I2C reads, or this C code directly
- Remove `sleep_ms()` — the hardware sensor read rate sets the natural timing
- Replace `printf()` notifications with: GPIO pin trigger, buzzer, LED, UART message, or BLE packet
- The entire detection logic (ring buffer + sliding window + state machine) fits in **< 4KB RAM** — suitable for Arduino Uno/Nano

### ✅ This is the final deployable version of the detection engine.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile step7_realtime.c
# #include <stdio.h>
# #include <stdlib.h>
# #include <string.h>
# #include <time.h>
# 
# /* ═══════════════════════════════════════════
#    Real-Time Turn Detection
#    Simulates live IMU feed row-by-row.
#    Fires notification the INSTANT a turn ends.
#    ═══════════════════════════════════════════ */
# 
# #define MAX_ROWS      5000
# #define MAX_COLS        20
# #define MAX_COL_LEN     64
# #define MAX_LINE_LEN   512
# 
# #define WINDOW_SIZE    40
# #define SMOOTH_K        5
# #define DEFAULT_DT   0.102
# #define MERGE_GAP      10
# 
# /* ── LEFT thresholds ── */
# #define L_STRICT_GX_MEAN  -4.0
# #define L_STRICT_GX_MIN  -12.0
# #define L_STRICT_GX_INT  -15.0
# #define L_RELAX_GX_MEAN   -3.0
# #define L_RELAX_GX_MIN   -10.0
# #define L_RELAX_GX_INT   -12.0
# #define L_RELAX_AZ_MEAN   -0.03
# 
# /* ── RIGHT thresholds ── */
# #define R_STRICT_GX_MEAN   4.0
# #define R_STRICT_GX_MAX   12.0
# #define R_STRICT_GX_INT   15.0
# #define R_RELAX_GX_MEAN    3.0
# #define R_RELAX_GX_MAX    10.0
# #define R_RELAX_GX_INT    12.0
# #define R_RELAX_AZ_MEAN    0.03
# 
# #define TURN_NONE   0
# #define TURN_LEFT   1
# #define TURN_RIGHT  2
# 
# /* ── simulate real-time delay (ms) ── */
# #define SIM_DELAY_MS  10   /* 10ms ≈ 100Hz, matching ~0.102s sample rate */
# 
# /* ── ring buffer for smoothing ── */
# typedef struct {
#     double buf[SMOOTH_K];
#     int    head;
#     int    count;
# } RingBuf;
# 
# void rb_push(RingBuf *rb, double val){
#     rb->buf[rb->head] = val;
#     rb->head = (rb->head + 1) % SMOOTH_K;
#     if(rb->count < SMOOTH_K) rb->count++;
# }
# double rb_mean(const RingBuf *rb){
#     double s = 0;
#     for(int i = 0; i < rb->count; i++) s += rb->buf[i];
#     return s / rb->count;
# }
# 
# /* ── sliding window state ── */
# typedef struct {
#     double gx_win[WINDOW_SIZE];
#     double az_win[WINDOW_SIZE];
#     int    head;
#     int    count;
# } SlidingWindow;
# 
# void sw_push(SlidingWindow *sw, double gx, double az){
#     sw->gx_win[sw->head] = gx;
#     sw->az_win[sw->head] = az;
#     sw->head = (sw->head + 1) % WINDOW_SIZE;
#     if(sw->count < WINDOW_SIZE) sw->count++;
# }
# 
# /* compute stats over full window */
# void sw_stats(const SlidingWindow *sw,
#               double *gx_mean, double *gx_ext,
#               double *az_mean, double dt,
#               double *gx_integral, int direction){
#     double gs = 0, az = 0;
#     double ext = sw->gx_win[0];
#     for(int i = 0; i < sw->count; i++){
#         gs  += sw->gx_win[i];
#         az  += sw->az_win[i];
#         if(direction == TURN_LEFT  && sw->gx_win[i] < ext) ext = sw->gx_win[i];
#         if(direction == TURN_RIGHT && sw->gx_win[i] > ext) ext = sw->gx_win[i];
#     }
#     *gx_mean     = gs / sw->count;
#     *gx_ext      = ext;
#     *az_mean     = az / sw->count;
#     *gx_integral = gs * dt;
# }
# 
# /* ── turn state machine ── */
# typedef struct {
#     int    active;          /* currently inside a turn? */
#     int    direction;       /* TURN_LEFT / TURN_RIGHT   */
#     int    start_idx;
#     int    last_trigger;    /* last row that fired      */
#     char   start_time[32];
#     double peak_gx;
#     double sum_gx;
#     int    sample_count;
# } TurnState;
# 
# void ts_init(TurnState *ts){
#     memset(ts, 0, sizeof(*ts));
# }
# 
# /* ════════════════════════════════════════
#    Notification
#    ════════════════════════════════════════ */
# void fire_notification(int event_id, int direction,
#                        const char *t_start, const char *t_end,
#                        double duration, double peak_gx,
#                        double rotation_deg){
#     const char *dir_str = (direction == TURN_LEFT)
#                           ? "LEFT  <<<" : "RIGHT >>>";
#     const char *arrow   = (direction == TURN_LEFT)
#                           ? "<-- *** YOU ARE TURNING LEFT  ***"
#                           : "--> *** YOU ARE TURNING RIGHT ***";
# 
#     printf("\n╔══════════════════════════════════════════════╗\n");
#     printf("║  🚗 REAL-TIME TURN ALERT  #%-3d               ║\n", event_id);
#     printf("╠══════════════════════════════════════════════╣\n");
#     printf("║  Direction : %-32s║\n", dir_str);
#     printf("║  %-44s║\n", arrow);
#     printf("║  Started   : %-32s║\n", t_start);
#     printf("║  Ended     : %-32s║\n", t_end);
#     printf("║  Duration  : %-6.2f s                         ║\n", duration);
#     printf("║  Peak GX   : %-8.2f dps                     ║\n", peak_gx);
#     printf("║  Rotation  : %-8.2f deg                     ║\n", rotation_deg);
#     printf("╚══════════════════════════════════════════════╝\n");
#     fflush(stdout);
# }
# 
# /* ════════════════════════════════════════
#    CSV helpers
#    ════════════════════════════════════════ */
# static int col_gx=-1, col_az=-1, col_ts=-1;
# 
# void clean_token(char *s){
#     int i=0; while(s[i]==' '||s[i]=='"') i++;
#     memmove(s,s+i,strlen(s+i)+1);
#     int len=(int)strlen(s);
#     while(len>0&&(s[len-1]==' '||s[len-1]=='"'||
#           s[len-1]=='\n'||s[len-1]=='\r')) s[--len]='\0';
# }
# void normalize(const char *src,char *dst,int maxlen){
#     int j=0;
#     for(int i=0;src[i]&&j<maxlen-1;i++){
#         char c=src[i]; if(c>='A'&&c<='Z') c+=32;
#         if(c==' '||c=='_'||c=='-'||c=='('||c==')'||c=='/') continue;
#         dst[j++]=c;
#     } dst[j]='\0';
# }
# int split_csv(char *line,char tokens[][MAX_COL_LEN],int max_tokens){
#     int count=0; char *p=line;
#     while(count<max_tokens){
#         char *start=p; while(*p&&*p!=',') p++;
#         int len=(int)(p-start); if(len>=MAX_COL_LEN) len=MAX_COL_LEN-1;
#         strncpy(tokens[count],start,len); tokens[count][len]='\0';
#         clean_token(tokens[count]); count++;
#         if(*p==',') p++; else break;
#     } return count;
# }
# int parse_header(char *line){
#     char tokens[MAX_COLS][MAX_COL_LEN];
#     int n=split_csv(line,tokens,MAX_COLS);
#     col_ts=col_gx=col_az=-1;
#     for(int i=0;i<n;i++){
#         char norm[MAX_COL_LEN]; normalize(tokens[i],norm,MAX_COL_LEN);
#         if(col_ts<0&&(strcmp(norm,"timestamp")==0||strcmp(norm,"time")==0||
#            strcmp(norm,"datetime")==0)) col_ts=i;
#         if(col_gx<0&&(strcmp(norm,"gxdps")==0||strcmp(norm,"gx")==0||
#            strcmp(norm,"gyrox")==0||strcmp(norm,"gyroxdps")==0)) col_gx=i;
#         if(col_az<0&&(strcmp(norm,"azg")==0||strcmp(norm,"az")==0||
#            strcmp(norm,"accz")==0||strcmp(norm,"accelz")==0)) col_az=i;
#     }
#     return (col_gx>=0&&col_az>=0)?0:-1;
# }
# 
# /* ════════════════════════════════════════
#    ms sleep (portable)
#    ════════════════════════════════════════ */
# void sleep_ms(int ms){
#     struct timespec ts;
#     ts.tv_sec  = ms / 1000;
#     ts.tv_nsec = (ms % 1000) * 1000000L;
#     nanosleep(&ts, NULL);
# }
# 
# /* ════════════════════════════════════════
#    MAIN — real-time loop
#    ════════════════════════════════════════ */
# int main(void){
#     const char *csv_path = "imu_6axis_data_20260308_084155_Trip2_Left.csv";
# 
#     FILE *f = fopen(csv_path, "r");
#     if(!f){ perror("fopen"); return 1; }
# 
#     char line[MAX_LINE_LEN];
# 
#     /* parse header */
#     if(!fgets(line, sizeof(line), f)){
#         fprintf(stderr,"Empty file\n"); fclose(f); return 1;
#     }
#     if(parse_header(line) != 0){
#         fprintf(stderr,"Required columns not found.\n"); fclose(f); return 1;
#     }
# 
#     printf("╔══════════════════════════════════════════════╗\n");
#     printf("║   REAL-TIME IMU TURN DETECTION SYSTEM        ║\n");
#     printf("║   Streaming CSV at ~%dms/sample (%dHz)        ║\n",
#            SIM_DELAY_MS, 1000/SIM_DELAY_MS);
#     printf("║   Watching for LEFT and RIGHT turns...       ║\n");
#     printf("╚══════════════════════════════════════════════╝\n\n");
#     fflush(stdout);
# 
#     /* ── per-direction state ── */
#     RingBuf    rb_gx, rb_az;
#     SlidingWindow sw;
#     TurnState  ts_left, ts_right;
# 
#     memset(&rb_gx, 0, sizeof(rb_gx));
#     memset(&rb_az, 0, sizeof(rb_az));
#     memset(&sw,    0, sizeof(sw));
#     ts_init(&ts_left);
#     ts_init(&ts_right);
# 
#     int row_idx    = 0;
#     int event_id   = 0;
#     double g_dt    = DEFAULT_DT;
#     char cur_ts[32] = {0};
# 
#     /* first pass: estimate dt from first 100 rows into memory */
#     double first_gx[100], first_az[100];
#     char   first_ts[100][32];
#     int    n_pre = 0;
# 
#     while(fgets(line,sizeof(line),f) && n_pre < 100){
#         char tokens[MAX_COLS][MAX_COL_LEN];
#         int n=split_csv(line,tokens,MAX_COLS);
#         if(n<=col_gx||n<=col_az) continue;
#         char *ep;
#         double gv=strtod(tokens[col_gx],&ep); if(ep==tokens[col_gx]) continue;
#         double av=strtod(tokens[col_az],&ep); if(ep==tokens[col_az]) continue;
#         first_gx[n_pre]=gv; first_az[n_pre]=av;
#         if(col_ts>=0&&n>col_ts)
#             strncpy(first_ts[n_pre],tokens[col_ts],31);
#         else snprintf(first_ts[n_pre],31,"row_%d",n_pre);
#         n_pre++;
#     }
# 
#     /* estimate dt */
#     {
#         double diffs[100]; int nd=0;
#         for(int i=1;i<n_pre;i++){
#             const char *a=first_ts[i-1],*b=first_ts[i];
#             int cc=0,pa=-1,pb=-1;
#             for(int k=0;a[k];k++) if(a[k]==':'){cc++;if(cc==2){pa=k+1;break;}}
#             cc=0;
#             for(int k=0;b[k];k++) if(b[k]==':'){cc++;if(cc==2){pb=k+1;break;}}
#             if(pa<0||pb<0) continue;
#             int mpa=-1,mpb=-1; cc=0;
#             for(int k=0;a[k];k++) if(a[k]==':'){cc++;if(cc==1){mpa=k+1;break;}}
#             cc=0;
#             for(int k=0;b[k];k++) if(b[k]==':'){cc++;if(cc==1){mpb=k+1;break;}}
#             double ta=strtod(a+mpa,NULL)*60+strtod(a+pa,NULL);
#             double tb=strtod(b+mpb,NULL)*60+strtod(b+pb,NULL);
#             double diff=tb-ta;
#             if(diff>0&&diff<2.0) diffs[nd++]=diff;
#         }
#         if(nd>0){
#             for(int i=1;i<nd;i++){
#                 double key=diffs[i]; int j=i-1;
#                 while(j>=0&&diffs[j]>key){diffs[j+1]=diffs[j];j--;}
#                 diffs[j+1]=key;
#             }
#             g_dt=diffs[nd/2];
#         }
#     }
#     printf("Estimated dt = %.4f s  |  Processing %d pre-loaded rows...\n\n",
#            g_dt, n_pre);
#     fflush(stdout);
# 
#     /* ── helper macro: check window + update state machine ── */
#     #define PROCESS_ROW(gx_val, az_val, ts_str, ridx)  do { \
#         rb_push(&rb_gx, (gx_val));                           \
#         rb_push(&rb_az, (az_val));                           \
#         double sgx = rb_mean(&rb_gx);                        \
#         double saz = rb_mean(&rb_az);                        \
#         sw_push(&sw, sgx, saz);                              \
#         strncpy(cur_ts, (ts_str), 31);                       \
#         if(sw.count == WINDOW_SIZE){                         \
#             /* --- check LEFT --- */                         \
#             double gxm,gxe,azm,gxi;                         \
#             sw_stats(&sw,&gxm,&gxe,&azm,g_dt,&gxi,TURN_LEFT); \
#             int L = (gxm<L_STRICT_GX_MEAN&&gxe<L_STRICT_GX_MIN&&gxi<L_STRICT_GX_INT) || \
#                     (gxm<L_RELAX_GX_MEAN &&gxe<L_RELAX_GX_MIN &&gxi<L_RELAX_GX_INT&&azm<L_RELAX_AZ_MEAN); \
#             if(L){                                           \
#                 if(!ts_left.active){                         \
#                     ts_left.active=1;                        \
#                     ts_left.start_idx=(ridx);                \
#                     strncpy(ts_left.start_time,(ts_str),31); \
#                     ts_left.peak_gx=gx_val;                  \
#                     ts_left.sum_gx=0; ts_left.sample_count=0;\
#                 }                                            \
#                 ts_left.last_trigger=(ridx);                 \
#                 if((gx_val)<ts_left.peak_gx) ts_left.peak_gx=(gx_val); \
#                 ts_left.sum_gx+=(gx_val); ts_left.sample_count++;       \
#             } else if(ts_left.active &&                      \
#                       (ridx)-ts_left.last_trigger > MERGE_GAP){ \
#                 event_id++;                                  \
#                 double dur=(ts_left.last_trigger-ts_left.start_idx+1)*g_dt; \
#                 double rot=ts_left.sum_gx*g_dt;             \
#                 fire_notification(event_id,TURN_LEFT,        \
#                     ts_left.start_time,(ts_str),dur,         \
#                     ts_left.peak_gx,rot);                    \
#                 ts_left.active=0;                            \
#             }                                                \
#             /* --- check RIGHT --- */                        \
#             sw_stats(&sw,&gxm,&gxe,&azm,g_dt,&gxi,TURN_RIGHT); \
#             int R = (gxm>R_STRICT_GX_MEAN&&gxe>R_STRICT_GX_MAX&&gxi>R_STRICT_GX_INT) || \
#                     (gxm>R_RELAX_GX_MEAN &&gxe>R_RELAX_GX_MAX &&gxi>R_RELAX_GX_INT&&azm>R_RELAX_AZ_MEAN); \
#             if(R){                                           \
#                 if(!ts_right.active){                        \
#                     ts_right.active=1;                       \
#                     ts_right.start_idx=(ridx);               \
#                     strncpy(ts_right.start_time,(ts_str),31);\
#                     ts_right.peak_gx=gx_val;                 \
#                     ts_right.sum_gx=0; ts_right.sample_count=0; \
#                 }                                            \
#                 ts_right.last_trigger=(ridx);                \
#                 if((gx_val)>ts_right.peak_gx) ts_right.peak_gx=(gx_val); \
#                 ts_right.sum_gx+=(gx_val); ts_right.sample_count++;      \
#             } else if(ts_right.active &&                     \
#                       (ridx)-ts_right.last_trigger > MERGE_GAP){ \
#                 event_id++;                                  \
#                 double dur=(ts_right.last_trigger-ts_right.start_idx+1)*g_dt; \
#                 double rot=ts_right.sum_gx*g_dt;            \
#                 fire_notification(event_id,TURN_RIGHT,       \
#                     ts_right.start_time,(ts_str),dur,        \
#                     ts_right.peak_gx,rot);                   \
#                 ts_right.active=0;                           \
#             }                                                \
#         }                                                    \
#         sleep_ms(SIM_DELAY_MS);                              \
#     } while(0)
# 
#     /* replay pre-loaded rows */
#     for(int i=0; i<n_pre; i++)
#         PROCESS_ROW(first_gx[i], first_az[i], first_ts[i], row_idx++);
# 
#     /* stream remaining rows live */
#     while(fgets(line, sizeof(line), f)){
#         char tokens[MAX_COLS][MAX_COL_LEN];
#         int n=split_csv(line,tokens,MAX_COLS);
#         if(n<=col_gx||n<=col_az) continue;
#         char *ep;
#         double gv=strtod(tokens[col_gx],&ep); if(ep==tokens[col_gx]) continue;
#         double av=strtod(tokens[col_az],&ep); if(ep==tokens[col_az]) continue;
#         char ts_str[32]="";
#         if(col_ts>=0&&n>col_ts) strncpy(ts_str,tokens[col_ts],31);
#         else snprintf(ts_str,31,"row_%d",row_idx);
# 
#         PROCESS_ROW(gv, av, ts_str, row_idx++);
# 
#         /* print live progress every 100 rows */
#         if(row_idx % 100 == 0){
#             printf("[%5d / ~1750]  ts=%-25s  gx=%8.3f\n",
#                    row_idx, cur_ts, gv);
#             fflush(stdout);
#         }
#     }
# 
#     /* flush any open turn at end of file */
#     if(ts_left.active){
#         event_id++;
#         double dur=(ts_left.last_trigger-ts_left.start_idx+1)*g_dt;
#         fire_notification(event_id, TURN_LEFT,
#             ts_left.start_time, cur_ts, dur,
#             ts_left.peak_gx, ts_left.sum_gx*g_dt);
#     }
#     if(ts_right.active){
#         event_id++;
#         double dur=(ts_right.last_trigger-ts_right.start_idx+1)*g_dt;
#         fire_notification(event_id, TURN_RIGHT,
#             ts_right.start_time, cur_ts, dur,
#             ts_right.peak_gx, ts_right.sum_gx*g_dt);
#     }
# 
#     fclose(f);
# 
#     printf("\n══════════════════════════════════════════════\n");
#     printf("  Stream complete.  %d rows processed.\n", row_idx);
#     printf("  Total turn events fired: %d\n", event_id);
#     printf("══════════════════════════════════════════════\n");
# 
#     return 0;
# }

!gcc step7_realtime.c -o step7 -lm
!./step7







